// src/app/screens/activity-feed/data.ts

export const statusCardsData = [
  {
    id: 1,
    title: 'ACTIVE VERIFICATIONS',
    value: '1,432',
    icon: 'verified_user',
    iconColor: 'text-[#0056D2]',
    iconBg: 'bg-[#e8f0fe]',
    subText: '12%',
    subIcon: 'arrow_upward',
    subColor: 'text-[#1b6d24]',
    isBadge: false,
  },
  {
    id: 2,
    title: 'AI PROCESSING QUEUE',
    value: '89',
    icon: 'psychology',
    iconColor: 'text-[#b06000]',
    iconBg: 'bg-[#fef7e0]',
    subText: 'items pending',
    subIcon: '',
    subColor: 'text-gray-500',
    isBadge: false,
  },
  {
    id: 3,
    title: 'WHATSAPP DELIVERY',
    value: '98.2%',
    icon: 'forum',
    iconColor: 'text-[#1b6d24]',
    iconBg: 'bg-[#e6f4ea]',
    subText: 'Optimal',
    subIcon: '',
    subColor: 'bg-[#e6f4ea] text-[#1b6d24]',
    isBadge: true,
  },
  {
    id: 4,
    title: 'PENDING OFFICER REVIEWS',
    value: '340',
    icon: 'assignment_late',
    iconColor: 'text-[#ba1a1a]',
    iconBg: 'bg-[#fce8e8]',
    subText: 'High',
    subIcon: '',
    subColor: 'bg-[#fce8e8] text-[#ba1a1a]',
    isBadge: true,
  },
];

export const feedEventsData = [
  {
    id: 1,
    type: 'error',
    icon: 'warning',
    iconBg: 'bg-[#fce8e8] text-[#ba1a1a]',
    title: 'AI Detection Triggered',
    time: '2 mins ago',
    citizen: 'Budi Santoso',
    detailBox: 'High economic change detected (-15%).',
    detailIcon: 'trending_down',
    detailBg: 'bg-[#fce8e8] text-[#ba1a1a] border-[#f9d2d2]',
  },
  {
    id: 2,
    type: 'neutral',
    icon: 'upload_file',
    iconBg: 'bg-gray-100 text-gray-500',
    title: 'Evidence Uploaded',
    time: '15 mins ago',
    citizen: 'Siti Aminah',
    detailBox: '3 documents verified.',
    detailIcon: 'description',
    detailBg: 'bg-gray-100 text-gray-600 border-gray-200',
  },
  {
    id: 3,
    type: 'success',
    icon: 'check_circle',
    iconBg: 'bg-[#e6f4ea] text-[#1b6d24]',
    title: 'Officer Approved',
    time: '1 hour ago',
    desc: 'Officer: A. Rahman approved Case #3201.',
  },
  {
    id: 4,
    type: 'primary',
    icon: 'chat',
    iconBg: 'bg-[#e8f0fe] text-[#0056D2]',
    title: 'WhatsApp Sent',
    time: '2 hours ago',
    desc: 'Verification link delivered to 1,240 citizens.',
  },
];

export const priorityEventsData = [
  {
    id: 1,
    badge: 'AI Escalated',
    badgeStyle: 'bg-[#fce8e8] text-[#ba1a1a]',
    borderStyle: 'border-l-[#ba1a1a]',
    title: 'High Priority: Anomaly Detected',
    desc: 'Concentration of unexpected applications in Surabaya region.',
    linkText: 'Investigate',
    linkColor: 'text-[#0056D2]',
  },
  {
    id: 2,
    badge: 'System Alert',
    badgeStyle: 'bg-[#fef7e0] text-[#b06000]',
    borderStyle: 'border-l-[#b06000]',
    title: 'Requires Attention',
    desc: '12 verification timeouts recorded in West Java data nodes.',
    linkText: 'View Logs',
    linkColor: 'text-[#b06000]',
  },
];